services:
  zincsearch:
    image: public.ecr.aws/zinclabs/zinc:0.4.1
    container_name: zincsearch
    environment:
      - ZINC_FIRST_ADMIN_USER=admin #zincsearch账号
      - ZINC_FIRST_ADMIN_PASSWORD=admin  #zincsearch密码
      - ZINC_DATA_PATH=/data
    volumes:
      - ./data:/data
    ports:
      - 14080:4080 #端口映射
    networks:
      - "logs-net"
  filebeat:
    image: elastic/filebeat:8.6.2
    container_name: filebeat
    environment:
      - ELASTICSEARCH_HOSTS=172.19.0.2:4080  #替换为zincsearch的IP 端口
      - ELASTICSEARCH_USERNAME=admin  #替换为zincsearch的账号
      - ELASTICSEARCH_PASSWORD=admin #替换为zincsearch的密码
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml  #filebeat配置文件
      - \code\platform_server\storage\logs:/var/log/platform_server/     #映射Log文件到filebeat 容器
      - \code\discount_server\storage\logs:/var/log/discount_server/     #映射Log文件到filebeat 容器
    networks:
      - "logs-net"
    depends_on:
      - "zincsearch"
networks:
  logs-net:
    external: true