filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  
setup.ilm.enabled: false
setup.template.overwrite: true
setup.template.enabled: true
setup.template.name: "whizcity"
setup.template.pattern: "whizcity-*"
filebeat.inputs:
- type: filestream
  id: platform
  paths:
    - /var/log/platform_server/*.log
    - /var/log/platform_server/operation/*.log
  fields:
     type: platform
output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  path: "/es/"
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
  index: "whizcity-%{[fields.type]}-%{+yyyy.MM.dd}"
  indices: 
    - index: whizcity-platform-%{+yyyy.MM.dd}
      when.equals:
         fields.type: platform   